

find_path ( LUAPLUS_INCLUDE_DIR ${LUAPLUS_HEADERS}
  PATH_SUFFIXES Src/LuaPlus
  PATHS  ${PROJECT_SOURCE_DIR}/${LUAPLUS_HOME} )
find_library ( LUAPLUS_LIB LuaPlus
  PATH_SUFFIXES Src/LuaPlus
  PATHS  ${PROJECT_SOURCE_DIR}/${LUAPLUS_HOME} )

if ( LUAPLUS_INCLUDE_DIR  AND LUAPLUS_LIB )
  set ( LUAPLUS_FOUND TRUE )
endif ( LUAPLUS_INCLUDE_DIR AND LUAPLUS_LIB )

include ( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS ( LuaPlus  DEFAULT_MSG LUAPLUS_LIB LUAPLUS_INCLUDE_DIR )

mark_as_advanced ( LUAPLUS_LIB LUAPLUS_INCLUDE_DIR )
